const iconMap: { keywords: string[]; icon: string }[] = [
  // Войны, битвы, конфликты
  {
    keywords: [
      'war',
      'battle',
      'army',
      'military',
      'conflict',
      'terror',
      'terrorism',
      'terrorist',
      'войн',
      'битв',
      'арми',
      'сражени',
      'войск',
      'боевые действия',
      'взятие',
      'фронт',
      'теракт',
      'террор',
      'террорист',
      'диктатор',
      'генерал',
      'campaign',
      'кампания',
      'siege',
      'осада',
      'интервенция',
    ],
    icon: 'i-lucide-swords',
  },
  // Рождение
  {
    keywords: [
      'birth',
      'born',
      'родился',
      'родилась',
      'рождение',
      'родившийся',
      'родились',
      'рожден',
    ],
    icon: 'i-lucide-baby',
  },
  // Смерть
  {
    keywords: [
      'death',
      'die',
      'passed away',
      'умер',
      'умерла',
      'скончался',
      'скончалась',
      'смерть',
      'погиб',
      'убит',
      'убийство',
    ],
    icon: 'i-lucide-heart-crack',
  },
  // Государи, президенты, власть
  {
    keywords: [
      'president',
      'king',
      'queen',
      'emperor',
      'monarch',
      'tsar',
      'царь',
      'король',
      'королева',
      'импер',
      'монарх',
      'президент',
      'правитель',
      'глава',
      'министр',
      'канцлер',
    ],
    icon: 'i-lucide-crown',
  },
  // Космос, ракеты, астрономия
  {
    keywords: [
      'space',
      'rocket',
      'moon',
      'satellite',
      'astronaut',
      'comet',
      'earth',
      'mars',
      'mercury',
      'venus',
      'jupiter',
      'uranus',
      'saturn',
      'космос',
      'ракета',
      'марс',
      'венера',
      'сатурн',
      'юпитер',
      'меркурий',
      'луна',
      'комет',
      'спутник',
      'астронавт',
      'космонавт',
      'звезда',
      'планета',
      'галактика',
      'spacecraft',
      'launch',
    ],
    icon: 'i-lucide-rocket',
  },
  // Музыка, искусство
  {
    keywords: [
      'music',
      'song',
      'concert',
      'composer',
      'artist',
      'sing',
      'museum',
      'art',
      'музыка',
      'песня',
      'композитор',
      'концерт',
      'артист',
      'живопись',
      'painting',
      'sculpture',
      'скульптура',
      'театр',
      'theater',
      'performance',
      'выставка',
    ],
    icon: 'i-lucide-theatre',
  },
  // Наука, изобретения
  {
    keywords: [
      'science',
      'invention',
      'inventor',
      'discovery',
      'исследование',
      'изобретение',
      'учёный',
      'наука',
      'открытие',
      'эксперимент',
      'experiment',
      'технология',
      'patent',
      'лауреат',
      'лауреаты',
      'nobel',
    ],
    icon: 'i-lucide-atom',
  },
  // Спорт
  {
    keywords: [
      'sports',
      'olympic',
      'game',
      'tournament',
      'match',
      'спорт',
      'олимпиада',
      'матч',
      'турнир',
      'игра',
      'футбол',
      'hockey',
      'наград',
      'trophy',
      'хоккей',
      'соревнование',
      'competition',
      'чемпионат',
      'cup',
      'league',
      'football',
      'soccer',
      'basketball',
      'swimming',
    ],
    icon: 'i-lucide-trophy',
  },
  // Пожары, катастрофы, стихийные бедствия
  {
    keywords: [
      'fire',
      'disaster',
      'earthquake',
      'flood',
      'explosion',
      'attack',
      'storm',
      'tsunami',
      'pandemic',
      'landslide',
      'crash',
      'авария',
      'атака',
      'пожар',
      'катастрофа',
      'землетрясение',
      'наводнение',
      'взрыв',
      'ураган',
      'цунами',
      'эпидемия',
      'завал',
      'обвал',
      'круш',
    ],
    icon: 'i-lucide-triangle-alert',
  },
  // Политика, революции, восстания
  {
    keywords: [
      'revolution',
      'rebellion',
      'coup',
      'политика',
      'революция',
      'восстание',
      'переворот',
      'мятеж',
      'демонстрация',
      'protest',
      'парламент',
      'выборы',
      'election',
      'сенат',
      'duma',
    ],
    icon: 'i-lucide-flag',
  },
  // Религия, церковь, святые
  {
    keywords: [
      'church',
      'religion',
      'saint',
      'cathedral',
      'церковь',
      'религия',
      'собор',
      'святой',
      'святая',
      'папа',
      'pope',
      'патриарх',
      'религиозный',
      'религиозная',
      'монастырь',
      'abbey',
      'монастырь',
    ],
    icon: 'i-lucide-church',
  },
  // Литература, книги
  {
    keywords: [
      'book',
      'novel',
      'literature',
      'writer',
      'poet',
      'книга',
      'роман',
      'литература',
      'писатель',
      'поэт',
      'повесть',
      'story',
      'автор',
      'publication',
      'журнал',
      'magazine',
      'газета',
      'newspaper',
    ],
    icon: 'i-lucide-book',
  },
  // Технологии, компьютеры
  {
    keywords: [
      'computer',
      'technology',
      'internet',
      'техника',
      'технология',
      'интернет',
      'компьютер',
      'айти',
      'робот',
      'robot',
      'software',
      'hardware',
      'искусственный интеллект',
      'ai',
      'программирование',
      'coding',
    ],
    icon: 'i-lucide-cpu',
  },
  // Экономика, финансы, бизнес
  {
    keywords: [
      'economy',
      'finance',
      'business',
      'stock',
      'market',
      'банк',
      'экономика',
      'финансы',
      'биржа',
      'рынок',
      'бизнес',
      'инвест',
      'инвестиции',
      'currency',
      'валюта',
      'деньги',
      'банкротство',
      'bankruptcy',
    ],
    icon: 'i-lucide-dollar-sign',
  },
  // Медицина, здоровье, болезни
  {
    keywords: [
      'medicine',
      'health',
      'doctor',
      'болезнь',
      'заболевание',
      'здоровье',
      'медицина',
      'лечить',
      'doctor',
      'врач',
      'hospital',
      'больница',
      'pandemic',
      'вакцина',
      'vaccine',
      'эпидемия',
    ],
    icon: 'i-lucide-heart-pulse',
  },
  // Транспорт, авиация, автомобили
  {
    keywords: [
      'transport',
      'aviation',
      'flight',
      'car',
      'plane',
      'train',
      'ship',
      'авиация',
      'самолет',
      'поезд',
      'корабль',
      'автомобиль',
      'транспорт',
      'рейс',
      'crash',
      'авиакатастрофа',
      'авария',
    ],
    icon: 'i-lucide-car',
  },
  // Кино, телевидение, медиа
  {
    keywords: [
      'cinema',
      'film',
      'movie',
      'tv',
      'series',
      'actor',
      'актёр',
      'актриса',
      'кино',
      'телевидение',
      'сериал',
      'фильм',
      'режиссёр',
      'premiere',
      'media',
      'медиа',
      'премьера',
    ],
    icon: 'i-lucide-clapperboard',
  },
  // Архитектура, здания, строительство
  {
    keywords: [
      'architecture',
      'building',
      'construction',
      'архитектура',
      'здание',
      'строительство',
      'построен',
      'постройка',
      'строить',
      'мост',
      'bridge',
      'skyscraper',
      'башня',
      'tower',
    ],
    icon: 'i-lucide-building-2',
  },
  // Путешествия, открытия земель, география
  {
    keywords: [
      'travel',
      'exploration',
      'expedition',
      'journey',
      'путешествие',
      'экспедиция',
      'открытие земель',
      'география',
      'исследование',
      'land',
      'continent',
      'остров',
      'island',
      'discover',
      'навигатор',
    ],
    icon: 'i-lucide-mountain-snow',
  },
  // Образование, школы, университеты
  {
    keywords: [
      'education',
      'school',
      'university',
      'college',
      'образование',
      'школ',
      'вуз',
      'университет',
      'институт',
      'студент',
      'учёба',
      'диссертация',
      'degree',
    ],
    icon: 'i-lucide-graduation-cap',
  },
  // Еда, напитки, кулинария
  {
    keywords: [
      'food',
      'drink',
      'cuisine',
      'еда',
      'напиток',
      'кулинария',
      'кухня',
      'ресторан',
      'кафе',
      'бар',
      'рецепт',
    ],
    icon: 'i-lucide-utensils-crossed',
  },
  // Открытия, находки
  {
    keywords: [
      'discovery',
      'found',
      'find',
      'открытие',
      'нашёл',
      'нашла',
      'обнаружил',
      'обнаружена',
      'раскопки',
      'excavation',
    ],
    icon: 'i-lucide-amphora',
  },
];

export default function PickTimeLineIcon(
  titles: string[],
  description: string
) {
  let text = '';
  for (const title of titles) text += title + ' ';
  text = (text + ' ' + description).toLowerCase();

  for (const entry of iconMap) {
    if (entry.keywords.some((word) => text.includes(word))) {
      return entry.icon;
    }
  }
  return 'i-lucide-earth';
}
