export const iconMap: { keywords: string[]; icon: string }[] = [
  // Смерть
  {
    keywords: [
      'смерт',
      'умер',
      'убийств',
      'траур',
      'гроб',
      'покойн',
      'скончал',
      'погиб',
      'похорон',
      'суицид',
      'death',
      'kill',
      'funer',
      'corpse',
      'mourning',
      'dead',
      'murder',
      'grave',
      'fatal',
      'suicid',
    ],
    icon: 'i-lucide-heart-crack',
  },
  // Войны, битвы, конфликты
  {
    keywords: [
      'войн',
      'битв',
      'конфликт',
      'арм',
      'генерал',
      'сражен',
      'фронт',
      'солдат',
      'разгром',
      'атака',
      'war',
      'battle',
      'conflict',
      'army',
      'soldier',
      'fight',
      'combat',
      'siege',
      'attack',
      'defeat',
    ],
    icon: 'i-lucide-swords',
  },
  // Государи, президенты, власть
  {
    keywords: [
      'государ',
      'президент',
      'монарх',
      'власт',
      'корол',
      'императ',
      'правител',
      'канцлер',
      'министр',
      'трон',
      'president',
      'king',
      'monarch',
      'ruler',
      'crown',
      'emperor',
      'chancellor',
      'minister',
      'throne',
      'sovereign',
    ],
    icon: 'i-lucide-crown',
  },
  // Космос, ракеты, астрономия
  {
    keywords: [
      'космос',
      'звезд',
      'ракет',
      'орбит',
      'астронавт',
      'спутник',
      'галакт',
      'планет',
      'солнечн',
      'комет',
      'space',
      'star',
      'rocket',
      'orbit',
      'astronaut',
      'satellit',
      'galax',
      'planet',
      'solar',
      'comet',
    ],
    icon: 'i-lucide-rocket',
  },
  // Музыка, искусство
  {
    keywords: [
      'музык',
      'песн',
      'инструмент',
      'театр',
      'поэз',
      'художн',
      'жанр',
      'балет',
      'композитор',
      'рисунок',
      'music',
      'song',
      'instrument',
      'art',
      'theatre',
      'artist',
      'genre',
      'ballet',
      'composer',
      'painting',
    ],
    icon: 'i-lucide-theater',
  },
  // Наука, изобретения
  {
    keywords: [
      'наук',
      'учен',
      'открыт',
      'эксперимент',
      'изобретен',
      'исследован',
      'теор',
      'гипотез',
      'физик',
      'лаборатор',
      'science',
      'discover',
      'invent',
      'experiment',
      'research',
      'theor',
      'hypoth',
      'physic',
      'laboratory',
      'innovation',
    ],
    icon: 'i-lucide-atom',
  },
  // Спорт
  {
    keywords: [
      'спорт',
      'матч',
      'команд',
      'побед',
      'чемпион',
      'игрок',
      'соревнован',
      'футбол',
      'тренер',
      'рекорд',
      'sport',
      'match',
      'team',
      'win',
      'champion',
      'player',
      'tournament',
      'football',
      'coach',
      'record',
    ],
    icon: 'i-lucide-trophy',
  },
  // Пожары, катастрофы, стихийные бедствия
  {
    keywords: [
      'пожар',
      'катастроф',
      'землетрясен',
      'ураган',
      'бедств',
      'наводнен',
      'авар',
      'буря',
      'трагед',
      'эпидем',
      'fire',
      'disaster',
      'earthquak',
      'hurrican',
      'flood',
      'accid',
      'storm',
      'traged',
      'epidem',
      'calamity',
    ],
    icon: 'i-lucide-triangle-alert',
  },
  // Политика, революции, восстания
  {
    keywords: [
      'революц',
      'восстан',
      'переворот',
      'политика',
      'выборы',
      'мятеж',
      'демонстрац',
      'парламент',
      'протест',
      'сенат',
      'revolution',
      'protest',
      'coup',
      'politic',
      'election',
      'rebellion',
      'parliament',
      'uprising',
      'senate',
      'duma',
    ],
    icon: 'i-lucide-flag',
  },
  // Религия, церковь, святые
  {
    keywords: [
      'религи',
      'церкв',
      'свят',
      'молитв',
      'икон',
      'православ',
      'католич',
      'епископ',
      'проповед',
      'храм',
      'religion',
      'church',
      'saint',
      'faith',
      'worship',
      'icon',
      'orthodox',
      'cathedr',
      'bishop',
      'sermon',
    ],
    icon: 'i-lucide-church',
  },
  // Технологии, компьютеры
  {
    keywords: [
      'технолог',
      'компьютер',
      'интернет',
      'программ',
      'робот',
      'сетев',
      'гаджет',
      'алгоритм',
      'драйвер',
      'систем',
      'tech',
      'computer',
      'internet',
      'program',
      'robot',
      'network',
      'gadget',
      'algorithm',
      'driver',
      'system',
    ],
    icon: 'i-lucide-cpu',
  },
  // Экономика, финансы, бизнес
  {
    keywords: [
      'экономик',
      'финанс',
      'бизнес',
      'доход',
      'рынок',
      'капитал',
      'банк',
      'налог',
      'инвестиц',
      'прибы',
      'econom',
      'financ',
      'busi',
      'profit',
      'market',
      'capital',
      'bank',
      'tax',
      'invest',
      'income',
    ],
    icon: 'i-lucide-dollar-sign',
  },
  // Медицина, здоровье, болезни
  {
    keywords: [
      'медицин',
      'болезн',
      'лечен',
      'врач',
      'пациент',
      'симптом',
      'диагноз',
      'терап',
      'лекарств',
      'вакцин',
      'health',
      'disease',
      'doctor',
      'patient',
      'vaccine',
      'symptom',
      'diagnos',
      'therapy',
      'drug',
      'illness',
    ],
    icon: 'i-lucide-heart-pulse',
  },
  // Транспорт, авиация, автомобили
  {
    keywords: [
      'транспорт',
      'авто',
      'самолет',
      'поезд',
      'дорог',
      'автобус',
      'грузовик',
      'метро',
      'порт',
      'рейс',
      'transport',
      'car',
      'plane',
      'train',
      'road',
      'bus',
      'truck',
      'metro',
      'port',
      'flight',
    ],
    icon: 'i-lucide-car',
  },
  // Кино, телевидение, медиа
  {
    keywords: [
      'кино',
      'фильм',
      'актер',
      'съемк',
      'телевиден',
      'режиссер',
      'сценар',
      'серия',
      'шоу',
      'эфир',
      'cinema',
      'film',
      'movie',
      'actor',
      'media',
      'director',
      'series',
      'show',
      'broadcast',
      'screenplay',
    ],
    icon: 'i-lucide-clapperboard',
  },
  // Архитектура, здания, строительство
  {
    keywords: [
      'архитектур',
      'здан',
      'строител',
      'дома',
      'ремонт',
      'фасад',
      'конструкц',
      'инженер',
      'материал',
      'проект',
      'architectur',
      'build',
      'construct',
      'house',
      'repair',
      'facade',
      'structure',
      'engineer',
      'material',
      'project',
    ],
    icon: 'i-lucide-building-2',
  },
  // Путешествия, открытия земель, география
  {
    keywords: [
      'путешеств',
      'открыт',
      'географ',
      'карта',
      'страна',
      'маршрут',
      'континент',
      'экспедиц',
      'туризм',
      'остров',
      'travel',
      'discover',
      'geograph',
      'map',
      'country',
      'route',
      'continent',
      'expedit',
      'tourism',
      'island',
    ],
    icon: 'i-lucide-mountain-snow',
  },
  // Растения, природа
  {
    keywords: [
      'природ',
      'растен',
      'дерево',
      'цветок',
      'лес',
      'куст',
      'трава',
      'плод',
      'ботаник',
      'семя',
      'nature',
      'plant',
      'tree',
      'flower',
      'forest',
      'bush',
      'grass',
      'fruit',
      'botany',
      'seed',
    ],
    icon: 'i-lucide-sprout',
  },
  // Образование, школы, университеты
  {
    keywords: [
      'образова',
      'школ',
      'университет',
      'студент',
      'учител',
      'лекц',
      'курс',
      'дисциплин',
      'экзамен',
      'диплом',
      'educat',
      'school',
      'universit',
      'student',
      'teacher',
      'lecture',
      'course',
      'subject',
      'exam',
      'diploma',
    ],
    icon: 'i-lucide-graduation-cap',
  },
  // Еда, напитки, кулинария
  {
    keywords: [
      'еда',
      'кулинар',
      'продукт',
      'повар',
      'напит',
      'рецепт',
      'фрукт',
      'овощ',
      'суп',
      'food',
      'dish',
      'cook',
      'recipe',
      'drink',
      'meat',
      'fruit',
      'vegetabl',
      'soup',
      'chef',
    ],
    icon: 'i-lucide-chef-hat',
  },
  // Открытия, находки
  {
    keywords: [
      'открыт',
      'обнаруж',
      'наход',
      'достижен',
      'раскоп',
      'археолог',
      'артефакт',
      'инновац',
      'сенсац',
      'выявлен',
      'discover',
      'find',
      'explor',
      'achievement',
      'artifact',
      'archaeolog',
      'innovation',
      'sensation',
      'identified',
      'uncover',
    ],
    icon: 'i-lucide-amphora',
  },
  // Литература, книги
  {
    keywords: [
      'литератур',
      'писател',
      'книг',
      'роман',
      'поэт',
      'читат',
      'эссе',
      'жанр',
      'драм',
      'автор',
      'literatur',
      'writer',
      'book',
      'novel',
      'poet',
      'read',
      'essay',
      'genre',
      'drama',
      'author',
    ],
    icon: 'i-lucide-book',
  },
  // Рождение
  {
    keywords: [
      'рожд',
      'дет',
      'младен',
      'семья',
      'матер',
      'отец',
      'беремен',
      'грудн',
      'родител',
      'потомств',
      'birth',
      'baby',
      'child',
      'family',
      'mother',
      'father',
      'pregnan',
      'newborn',
      'parent',
      'offspr',
    ],
    icon: 'i-lucide-baby',
  },
];

export default function PickTimeLineIcon(
  titles: string[],
  description: string
) {
  let text = '';
  for (const title of titles) text += title + ' ';
  text = (text + ' ' + description).toLowerCase();

  for (const entry of iconMap) {
    if (entry.keywords.some((word) => text.includes(word))) {
      return entry.icon;
    }
  }
  return 'i-lucide-earth';
}
